### ISSUE TITLE
Linux version 2.0.9 stuck on "Initiate configurations"

### ISSUE THREAD

**Issue by selahlynch** [jianlins/EasyCIE_GUI#1]
I'm trying to run EasyCIE as downloaded from the "smoke" Google drive, using the linux version from "EasyCIE_2.0.9_linux_jdk.zip".  I'm running on a CentOS release 6.10 linux server using X11 forwarding.

I was able to import text files with no concerns.  However, when I press the "RunEasyCIE" button at the bottom of the "easycie" screen, I am stuck on status "Initiate configurations" for indefinitely.  When I look at my terminal I see the following output:

```
Totally 64 documents have been imported successfully.
Jun 28, 2019 12:12:15 PM org.apache.uima.tools.jcasgen.UimaLoggerProgressMonitor subTask(35)
INFO:  >>JCasGen Output going to memory
Jun 28, 2019 12:12:15 PM org.apache.uima.tools.jcasgen.UimaLoggerProgressMonitor subTask(35)
INFO:  >>JCasGen Reading the XML TAE descriptor, and creating types, for xml input file 'desc/type/smoke_cpe_v2_Type.xml'.
Jun 28, 2019 12:12:15 PM org.apache.uima.tools.jcasgen.UimaLoggerProgressMonitor done(31)
INFO:  ** JCasGen Done.
java.lang.IllegalAccessError: tried to access method org.apache.uima.collection.impl.CollectionProcessingEngine_impl.getCPM()Lorg/apache/uima/collection/impl/cpm/BaseCPMImpl; from class edu.utah.bmi.nlp.uima.AdaptableCPEDescriptorRunner
	at edu.utah.bmi.nlp.uima.AdaptableCPEDescriptorRunner.updateCpeProcessorConfiguration(AdaptableCPEDescriptorRunner.java:1040)
	at edu.utah.bmi.nlp.uima.AdaptableCPEDescriptorRunner.compileCPE(AdaptableCPEDescriptorRunner.java:1194)
	at edu.utah.bmi.nlp.uima.AdaptableCPEDescriptorRunner.run(AdaptableCPEDescriptorRunner.java:1217)
	at edu.utah.bmi.simple.gui.task.RunCPEDescriptorTask.call(RunCPEDescriptorTask.java:154)
	at javafx.concurrents.Task$TaskCallable.call(Task.java:1002)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

Please let me know if there is any other information that would be useful, and if you have any suggestions of how to remedy this.  Thank you!

**Comment by jianlins** [comment]
Sorry for missing this issue. Will you be able to solve the problem. A few updates came afterwards.
